### PR TITLE
Add /verifiedProjectsGiversReport

### PR DESCRIPTION
**Pull request by mohammadranjbarz**

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
related to Giveth/giveth-dapp#2253

**Comment by mohammadranjbarz** [comment]
It should be the API
`/verifiedProjectsGiversReport?fromDate=2018/09/01-00:00:00&toDate=2021/01/01-00:00:00`
* The verified projects are defined in DB (Currenlt we can manually set `verified` for projects in DB
* If a campaign is `verified` we assume the campaign's traces are `verified`
* The response is something like this:
```
{
    "total": 44,
    "from": "2018-08-31T19:30:00.000Z",
    "to": "2020-12-31T20:30:00.000Z",
    "verifiedProjectIds": [
        "5"
    ],
    "data": [
        {
            "totalAmount": 1303.21,
            "donations": [
                {
                    "usdValue": 1303.21,
                    "amount": 6.892,
                    "createdAt": "2019-11-06T20:40:04.000Z",
                    "homeTxHash": "0x0fb0fceda96932265774caef6e2afb24f97e599b018a9849b7889690f2ace050",
                    "token": "ETH",
                    "projectId": 5
                }
            ],
            "giverAddress": "0x1d64db334E15E753123dD39d32fcE425Fa529Fc4"
        },
        {
            "totalAmount": 7158.75,
            "donations": [
                {
                    "usdValue": 3432.5,
                    "amount": 25,
                    "createdAt": "2018-11-22T01:08:52.000Z",
                    "homeTxHash": "0xbe9b7ae792c943cdaa36bea8d8edefb6a84e50f69b3c675e7012366e4f250ec1",
                    "token": "ETH",
                    "projectId": 5
                },
                {
                    "usdValue": 3726.25,
                    "amount": 25,
                    "createdAt": "2019-02-23T13:13:25.000Z",
                    "homeTxHash": "0x00cc854039fa3e4f9d9aabf404060f20d897fe03b2752932d5d246c6e4c0d749",
                    "token": "ETH",
                    "projectId": 5
                }
            ],
            "giverAddress": "0xc38f6a88B03fb2322D9815F043b5713AFc3AAD49"
        }
    ]
}

```
* Currenty for Communities we calculate the moneys that has been donated to Community, but maybe we should change the logic to return the moneys that delegated from Community to Trace or Campaign

**Comment by aminlatifi** [comment]
@mohammadranjbarz I ran below query on trace to get donations of Dapp Development Campaign.
```
db.getCollection('donations').aggregate([
    {
      $match: {
        status: {
          $in: ['Waiting', 'Committed'],
        },

        homeTxHash: { $exists: true },
        $or: [
          {
            // it's for communities
            delegateId: { $in: [9] },
            intendedProjectId: { $exists: false },
          },

          // it's for traces and campaigns
          { ownerId: { $in: [9] } },
        ],
        amount: { $ne: '0' },
        usdValue: { $ne: 0 },
        isReturn: false,
      },
    },

    {
      $group: {
        _id: '$giverAddress',
        totalAmount: { $sum: '$usdValue' },
        donationIds: { $push: '$_id' },
      },
    },
    {
      $lookup: {
        from: 'donations',
        let: { donationIds: '$donationIds' },
        pipeline: [
          {
            $match: { $expr: { $in: ['$_id', '$$donationIds'] } },
          },
          {
            $project: {
              _id: 0,
              createdAt: 1,
              tokenAddress: 1,
              usdValue: 1,
              amount: 1,
              homeTxHash: 1,
              delegateId: 1,
              ownerId: 1,
            },
          },
        ],
        as: 'donations',
      },
    },
    {
      $project: {
        giverAddress: '$_id',
        donations: 1,
        totalAmount: 1,
        _id: 0,
      },
    },
  ]);```

This query is extracted from this PR and fetched donations and donors. The result is not correct.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I ran below query on trace to get donations of Dapp Development Campaign.
> 
> ```
> db.getCollection('donations').aggregate([
>     {
>       $match: {
>         status: {
>           $in: ['Waiting', 'Committed'],
>         },
> 
>         homeTxHash: { $exists: true },
>         $or: [
>           {
>             // it's for communities
>             delegateId: { $in: [9] },
>             intendedProjectId: { $exists: false },
>           },
> 
>           // it's for traces and campaigns
>           { ownerId: { $in: [9] } },
>         ],
>         amount: { $ne: '0' },
>         usdValue: { $ne: 0 },
>         isReturn: false,
>       },
>     },
> 
>     {
>       $group: {
>         _id: '$giverAddress',
>         totalAmount: { $sum: '$usdValue' },
>         donationIds: { $push: '$_id' },
>       },
>     },
>     {
>       $lookup: {
>         from: 'donations',
>         let: { donationIds: '$donationIds' },
>         pipeline: [
>           {
>             $match: { $expr: { $in: ['$_id', '$$donationIds'] } },
>           },
>           {
>             $project: {
>               _id: 0,
>               createdAt: 1,
>               tokenAddress: 1,
>               usdValue: 1,
>               amount: 1,
>               homeTxHash: 1,
>               delegateId: 1,
>               ownerId: 1,
>             },
>           },
>         ],
>         as: 'donations',
>       },
>     },
>     {
>       $project: {
>         giverAddress: '$_id',
>         donations: 1,
>         totalAmount: 1,
>         _id: 0,
>       },
>     },
>   ]);```
> 
> This query is extracted from this PR and fetched donations and donors. The result is not correct.
> ```
@aminlatifi 
I don't return the query response directly, I do some processes on that as below:
https://github.com/Giveth/feathers-giveth/pull/521/files#diff-b445b47dd4d2a7a4b13d66b851eb16188181aa8bc9b1959e96b4d34885d313f5R40-R51

**Comment by aminlatifi** [comment]
> > @mohammadranjbarz I ran below query on trace to get donations of Dapp Development Campaign.
> > ```
> > db.getCollection('donations').aggregate([
> >     {
> >       $match: {
> >         status: {
> >           $in: ['Waiting', 'Committed'],
> >         },
> > 
> >         homeTxHash: { $exists: true },
> >         $or: [
> >           {
> >             // it's for communities
> >             delegateId: { $in: [9] },
> >             intendedProjectId: { $exists: false },
> >           },
> > 
> >           // it's for traces and campaigns
> >           { ownerId: { $in: [9] } },
> >         ],
> >         amount: { $ne: '0' },
> >         usdValue: { $ne: 0 },
> >         isReturn: false,
> >       },
> >     },
> > 
> >     {
> >       $group: {
> >         _id: '$giverAddress',
> >         totalAmount: { $sum: '$usdValue' },
> >         donationIds: { $push: '$_id' },
> >       },
> >     },
> >     {
> >       $lookup: {
> >         from: 'donations',
> >         let: { donationIds: '$donationIds' },
> >         pipeline: [
> >           {
> >             $match: { $expr: { $in: ['$_id', '$$donationIds'] } },
> >           },
> >           {
> >             $project: {
> >               _id: 0,
> >               createdAt: 1,
> >               tokenAddress: 1,
> >               usdValue: 1,
> >               amount: 1,
> >               homeTxHash: 1,
> >               delegateId: 1,
> >               ownerId: 1,
> >             },
> >           },
> >         ],
> >         as: 'donations',
> >       },
> >     },
> >     {
> >       $project: {
> >         giverAddress: '$_id',
> >         donations: 1,
> >         totalAmount: 1,
> >         _id: 0,
> >       },
> >     },
> >   ]);```
> > 
> > This query is extracted from this PR and fetched donations and donors. The result is not correct.
> > ```
> 
> @aminlatifi
> I don't return the query response directly, I do some processes on that as below:
> https://github.com/Giveth/feathers-giveth/pull/521/files#diff-b445b47dd4d2a7a4b13d66b851eb16188181aa8bc9b1959e96b4d34885d313f5R40-R51

Yeah, but the number of records (donations per user) and total values are different

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I changed Giveth-dapp campaign and Common-stack community verified, and this is the response 
`/verifiedProjectsGiversReport?fromDate=2018/09/01-00:00:00&toDate=2021/01/01-00:00:00`
https://gist.github.com/mohammadranjbarz/418db9a6c6da67c6ec39a2e69b496830

**Comment by aminlatifi** [comment]
Good job @mohammadranjbarz

**Comment by aminlatifi** [comment]
@mohammadranjbarz Can you generate another output from latest updated?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Can you generate another output from latest updated?

Sure

* verified projects:
https://gist.githubusercontent.com/mohammadranjbarz/a094b6008e5b618b91d5834bec0a3ddd/raw/67eb8410be6a8c49741e1950aa31c66fa259e1c3/Verified%2520projects%2520(Giveth-dapp%2520campaign)

* All projects:
https://gist.github.com/mohammadranjbarz/a094b6008e5b618b91d5834bec0a3ddd#file-all-projects

**Comment by aminlatifi** [comment]
Thanks @mohammadranjbarz it was great.

**Pull request merged**
