### PR TITLE
Add donations create/update diagram

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to giveth/giveth-dapp#1825

### CODE REVIEW

**Comment by aminlatifi** [comment]
@mohammadranjbarz I updated diagram based on my knowledge, but it's important to test scenarios. Specially rejecting donations delegated by a community

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
As you can see  when a `ToApprove` donation became rejected, a `Waiting` donation will be created so I changed the Solid arrow from rejected to communityWaiting
Screen Shot 1400-06-10 at 14 47 18

**Comment by mohammadranjbarz** [comment]
You can search `612b393c3baf41001cf500e9` in Kibana to see what happened after rejecting donation
@aminlatifi

**Comment by aminlatifi** [comment]
> @aminlatifi
> As you can see when a `ToApprove` donation became rejected, a `Waiting` donation will be created so I changed the Solid arrow from rejected to communityWaiting
> Screen Shot 1400-06-10 at 14 47 18

Thanks, would you please add label to reject decision
image

**Comment by aminlatifi** [comment]
> > > @aminlatifi
> > > As you can see when a `ToApprove` donation became rejected, a `Waiting` donation will be created so I changed the Solid arrow from rejected to communityWaiting
> > > Screen Shot 1400-06-10 at 14 47 18
> > 
> > 
> > Thanks, would you please add label to reject decision
> > image
> 
> @aminlatifi done

Thanks

**Pull request merged**
