### PR TITLE
Fix error decoding bridge events

### PR DESCRIPTION
**Pull request by dapplion**
Patches `@ethersproject/abi`, to fix this issue https://github.com/ethers-io/ethers.js/issues/992#issuecomment-671069313

Haven't tested it outside of a sample script, please make sure it actually fixes the problem.

#### Afterwards

Track issue and once it's fixed bump library and remove patch-package

### CODE REVIEW

**Comment by aminlatifi** [comment]
Great work @dapplion

**Comment by aminlatifi** [comment]
Simulation script does not work as expected though

**Comment by dapplion** [comment]
@aminlatifi Can you paste here error logs and more info about why not?

**Comment by aminlatifi** [comment]
> @aminlatifi Can you paste here error logs and more info about why not?

It has been solved, not related to your update

**Comment by ricmoo** [comment]
I've added support in ethers [5.0.12](https://github.com/ethers-io/ethers.js/releases/tag/v5.0.12) for supporting legacy Solidity 0.4 external event data.

A quick note regarding this PR: You should only enable loose parsing for events. Attempting to parse call results with a loose parser is not possible (and unsafe) since incorrectly formatted call data could possibly be an error parsed as a non-error or a non-error parsed as an error (e.g. if a call result had a `bytes` of length 4, the data as a whole would be interpreted as an EIP-838 error, and the decoding would begin at the wrong position).

For more details, please see https://github.com/ethers-io/ethers.js/issues/891.

**Pull request merged**
