### PR TITLE
Convert tokens to stableCoin if rateEqSymbol of coin is stable

### LINKED ISSUE #318: Something wrong about conversion rate on develop
image
https://develop.giveth.io/campaigns/5f816dfb1670ac716d805ad8

Above donations in `XDAI` should have the same rate as `DAI`, and since `DAI` is stable coin they rate should be exactly 1 USD.

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
Fix #318

I think the problem of #318  was because this:
* `DAI` is a stable coin
* `XDAI` is not a stable coin, but `rateEqSymbol` of `XDAI` token  is `DAI`
* In conversionRate we were checking if token is a stable coin we return exactly 1, but the `XDAI` is not stable itself

I fixed this issue by checking if rateEqSymbol token of a token is stable coin we do same behaviour of a stable coin

### CODE REVIEW

**Comment by aminlatifi** [comment]
@mohammadranjbarz Thanks for your fast pull request to fix the issue... after our last discussion I believe you are right... it's better to remove stableCoins array in config, we have better solution `rateEqSymbol` now :)
Let's remove stable coins list forever and just set `USD` as their rateEqSymbol value.

**Comment by aminlatifi** [comment]
> @mohammadranjbarz Thanks for your fast pull request to fix the issue... after our last discussion I believe you are right... it's better to remove stableCoins array in config, we have better solution `rateEqSymbol` now :)
> Let's remove stable coins list forever and just set `USD` as their `rateEqSymbol` value.

It will make the backend more simple and it's valuable since the conversion rate service has become complex

**Comment by mohammadranjbarz** [comment]
> > @mohammadranjbarz Thanks for your fast pull request to fix the issue... after our last discussion I believe you are right... it's better to remove stableCoins array in config, we have better solution `rateEqSymbol` now :)
> > Let's remove stable coins list forever and just set `USD` as their `rateEqSymbol` value.
> 
> It will make the backend more simple and it's valuable since the conversion rate service has become complex

Yes it's better

**Comment by aminlatifi** [comment]
> > > @mohammadranjbarz Thanks for your fast pull request to fix the issue... after our last discussion I believe you are right... it's better to remove stableCoins array in config, we have better solution `rateEqSymbol` now :)
> > > Let's remove stable coins list forever and just set `USD` as their `rateEqSymbol` value.
> > 
> > 
> > It will make the backend more simple and it's valuable since the conversion rate service has become complex
> 
> Yes it's better Amin, I'm agree with you,
> do you want the changes of removing stable coins be in this pull request or I should make another pull request for those changes?

Please update this one

**Comment by mohammadranjbarz** [comment]
> > > > @mohammadranjbarz Thanks for your fast pull request to fix the issue... after our last discussion I believe you are right... it's better to remove stableCoins array in config, we have better solution `rateEqSymbol` now :)
> > > > Let's remove stable coins list forever and just set `USD` as their `rateEqSymbol` value.
> > > 
> > > 
> > > It will make the backend more simple and it's valuable since the conversion rate service has become complex
> > 
> > 
> > Yes it's better Amin, I'm agree with you,
> > do you want the changes of removing stable coins be in this pull request or I should make another pull request for those changes?
> 
> Please update this one

@aminlatifi 

All stuff related to stableCoins deleted now and all the things handles with `rateEqSymbol`

**Pull request merged**
