### PR TITLE
F 314 improve find conflicts simulation script

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
@aminlatifi  It's not completed but I created the PR so you can see and give me feedbacks about that, 
now the donations, milestones, dacs, campaigns, and pledgeAdmin will be created by fetched events, 
* Caching state events implemented
* It's written in typescript
* The error doesn't occur , I ran many times
* This subproject can run stand alone without any depndency to `./src` directory
* Email the report to mailList ( its not-completed)
* Code needs more refactor

This the first time I ran ( not from scratch, there were some cache events)

image

This the running script after the previous one:

image

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
I didn't use `web3Helper` for instantiating the web3 ( because it was a little different to findConflicts and needed changes, because the instantiatingWeb3 in findConflicts should be async)
but I export `reconnectOnEnd` and added that to findConflicts 
@aminlatifi

**Comment by mohammadranjbarz** [comment]
@aminlatifi now the simulation can be a separate module for running that you just navigate to `simulation` directory an then :
* npm i
* put a config folder in `simulation`
* npm start 

It transpile the ts files to js and then run it with node js, and it has no dependency to feathers code so even it can be another project anytime we want

**Comment by mohammadranjbarz** [comment]
TODO : 
* get transaction timestamp like web3Helper and not fetching fro network every time
* websocket provider (web3Provider)

**Comment by mohammadranjbarz** [comment]
> TODO :
> 
> * get transaction timestamp like web3Helper and not fetching fro network every time
> * websocket provider (web3Provider)

@aminlatifi 
If I remember correctly, you said we used `web3-providers-ws` in somewhere and I should use that strategy in simulation, but I can't find any usage of this package in code, I would appreciate if you code say me where is the usage example in our project

**Comment by aminlatifi** [comment]
> > TODO :
> > 
> > * get transaction timestamp like web3Helper and not fetching fro network every time
> > * websocket provider (web3Provider)
> 
> @aminlatifi
> If I remember correctly, you said we used `web3-providers-ws` in somewhere and I should use that strategy in simulation, but I can't find any usage of this package in code, I would appreciate if you code say me where is the usage example in our project

It's here 
https://github.com/Giveth/feathers-giveth/blob/2a5ab14bb32c4fcb0aa14f1a32522680c73b2a13/scripts/utils/findConflicts.js#L16

It would be better if you rebase/merge develop to your branch

**Comment by mohammadranjbarz** [comment]
> > > TODO :
> > > 
> > > * get transaction timestamp like web3Helper and not fetching fro network every time
> > > * websocket provider (web3Provider)
> > 
> > 
> > @aminlatifi
> > If I remember correctly, you said we used `web3-providers-ws` in somewhere and I should use that strategy in simulation, but I can't find any usage of this package in code, I would appreciate if you code say me where is the usage example in our project
> 
> It's here
> https://github.com/Giveth/feathers-giveth/blob/2a5ab14bb32c4fcb0aa14f1a32522680c73b2a13/scripts/utils/findConflicts.js#L16
> 
> It would be better if you rebase/merge develop to your branch

Thanks, it was my fault I was searching in `src` directory not `scripts`

**Comment by mohammadranjbarz** [comment]
Fix #314

**Comment by aminlatifi** [comment]
Implement changes of this commit to simulation project to 
https://github.com/Giveth/feathers-giveth/pull/348/commits/233de079b42cdc613b965523410450a9fedf3e72

**Comment by aminlatifi** [comment]
@mohammadranjbarz Please 
* Upload whole the simulation script to this repo https://github.com/Giveth/giveth-1-simulation
* User cursor for reading donations, the number of them can be huge
* Modularize current functions and components, the index.ts is spaghetti

**Comment by aminlatifi** [comment]
All the simulation script codes moved to https://github.com/giveth/giveth-1-simulation repo

**Pull request closed without merging**
