### PR TITLE
Add sentry for crash reporting

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to Giveth/giveth-dapp#2303
https://github.com/feathersjs/feathers/discussions/2406

@aminlatifi For merging this we should create an account in Sentry and add `sentryDsn` to config

### CODE REVIEW

**Review by aminlatifi — CHANGES_REQUESTED** [review]
Thanks @mohammadranjbarz, nice job. Just two points:
1. If `sentryDsn` be empty what will happen? can user run application without config?
2. I guess we will miss these lines logic when an error happens
```
    let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
    if (hook.type === 'error') {
      message += ` - ${hook.error.message}`;
    }

    if (hook.params.provider && hook.type !== 'error') {
      logger.debug(message);
    } else if (hook.params.provider && hook.type === 'error') {
      logger.info(message);
    } else {
      logger.debug(`INTERNAL_CALL -> ${message}`);
    }
    logger.debug('hook.data', hook.data);
    logger.debug('hook.params', hook.params);
    if (hook.result) {
      logger.debug('hook.result', hook.result);
    }
 ```
I mean the lines will be printed are informative and better to keep them in our internal log. What do you think?

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz, nice job. Just two points:
> 
> 1. If `sentryDsn` be empty what will happen? can user run application without config?
> 2. I guess we will miss these lines logic when an error happens
> 
> ```
>     let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
>     if (hook.type === 'error') {
>       message += ` - ${hook.error.message}`;
>     }
> 
>     if (hook.params.provider && hook.type !== 'error') {
>       logger.debug(message);
>     } else if (hook.params.provider && hook.type === 'error') {
>       logger.info(message);
>     } else {
>       logger.debug(`INTERNAL_CALL -> ${message}`);
>     }
>     logger.debug('hook.data', hook.data);
>     logger.debug('hook.params', hook.params);
>     if (hook.result) {
>       logger.debug('hook.result', hook.result);
>     }
> ```
> 
> I mean the lines will be printed are informative and better to keep them in our internal log. What do you think?

1. No it has no problem, you can run it without sentrDsn
2. in errorHandlerHook we log errors ( after  Sentry.captureException(e), the rest of function will be execute)

**Comment by aminlatifi** [comment]
> > Thanks @mohammadranjbarz, nice job. Just two points:
> > 
> > 1. If `sentryDsn` be empty what will happen? can user run application without config?
> > 2. I guess we will miss these lines logic when an error happens
> > 
> > ```
> >     let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
> >     if (hook.type === 'error') {
> >       message += ` - ${hook.error.message}`;
> >     }
> > 
> >     if (hook.params.provider && hook.type !== 'error') {
> >       logger.debug(message);
> >     } else if (hook.params.provider && hook.type === 'error') {
> >       logger.info(message);
> >     } else {
> >       logger.debug(`INTERNAL_CALL -> ${message}`);
> >     }
> >     logger.debug('hook.data', hook.data);
> >     logger.debug('hook.params', hook.params);
> >     if (hook.result) {
> >       logger.debug('hook.result', hook.result);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I mean the lines will be printed are informative and better to keep them in our internal log. What do you think?
> > @aminlatifi
> 
> 1. No it has no problem, you can run it without sentrDsn
> 2. in errorHandlerHook we log errors ( after  Sentry.captureException(e), the rest of function will be execute) (previously we had one hook for logging success response and error responses, I separated them and move it to errorHandler)

I meant information added like this
```
    let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
```

**Comment by mohammadranjbarz** [comment]
> > > Thanks @mohammadranjbarz, nice job. Just two points:
> > > 
> > > 1. If `sentryDsn` be empty what will happen? can user run application without config?
> > > 2. I guess we will miss these lines logic when an error happens
> > > 
> > > ```
> > >     let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
> > >     if (hook.type === 'error') {
> > >       message += ` - ${hook.error.message}`;
> > >     }
> > > 
> > >     if (hook.params.provider && hook.type !== 'error') {
> > >       logger.debug(message);
> > >     } else if (hook.params.provider && hook.type === 'error') {
> > >       logger.info(message);
> > >     } else {
> > >       logger.debug(`INTERNAL_CALL -> ${message}`);
> > >     }
> > >     logger.debug('hook.data', hook.data);
> > >     logger.debug('hook.params', hook.params);
> > >     if (hook.result) {
> > >       logger.debug('hook.result', hook.result);
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I mean the lines will be printed are informative and better to keep them in our internal log. What do you think?
> > > @aminlatifi
> > 
> > 
> > 
> > 1. No it has no problem, you can run it without sentrDsn
> > 2. in errorHandlerHook we log errors ( after  Sentry.captureException(e), the rest of function will be execute) (previously we had one hook for logging success response and error responses, I separated them and move it to errorHandler)
> 
> I meant information added like this
> 
> ```
>     let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
> ```

Got it, 
I'll make change and push another commit

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I've put back the the error logger into previous logger function

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I pushed some commits after your review, please take a look to them before merging

**Pull request merged**
